
quarkus.jackson.serialization.write-dates-as-timestamps=false

# ===== DATASOURCE =====
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=<YOUR-DB-USERNAME>
quarkus.datasource.password=<YOUR-DB-PASSWORD>

quarkus.datasource.jdbc.url=jdbc:postgresql://<HOST>:<PORT>/<DB-NAME>

# ===== HIBERNATE =====
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# ===== REDIS =====
quarkus.redis.hosts=redis://<HOST>:<PORT>
